#!/usr/bin/env ruby

$LOAD_PATH.unshift File.expand_path('../lib', __dir__)
require 'scampi'

ENV["TEST"] = "true"

files = if ARGV.empty?
          # Auto-discover files carrying co-located tests in an __END__ section.
          `rg -l "^__END__$" .`.split("\n").select { |f|
            next false unless f.end_with?('.rb')
            tail = File.read(f).split(/^__END__$\n?/, 2)[1]
            tail && tail =~ /^\s*(describe|context|shared|it)\b/
          }
        else
          ARGV.flat_map { |pattern| Dir.glob(pattern) }
        end

if files.empty?
  $stderr.puts "no test files found"
  exit 1
end

files.each { |file| Scampi.load_test_file(file) }

Scampi.run
exit(Scampi::Counter[:errors] + Scampi::Counter[:failed] > 0 ? 1 : 0)
